#!/usr/bin/with-contenv bash

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 80" \
        s6-setuidgid abc java \
            -jar \
            -Dserver.port=80 \  # Explicitly set the server to listen on port 80
            -Dconfig.file=/config/ha-bridge.config \
            -Dexec.garden=/config/scripts \
            -Dsecurity.key="$SEC_KEY" \
            /app/ha-bridge.jar